inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/CommentedKeyword:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Layout/LineLength:
  Max: 120
