name: Rspec
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.4', '3.2']
    steps:
      - uses: actions/checkout@v3
      - name: Setup git access
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com: && \
          git config --global url."https://".insteadOf git://
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
  styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup git access
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com: && \
          git config --global url."https://".insteadOf git://
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1  # Use the latest version instead of pinned commit
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Rubocop
        run: bundle exec rubocop

